spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  datasource:
    initialization-mode: never

---
spring:
  config.activate.on-profile: test
  datasource:
    initialization-mode: embedded
  flyway:
    enabled: false
