spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
  datasource:
    initialization-mode: never
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring:
  profiles: test
  datasource:
    initialization-mode: embedded
  flyway:
    enabled: false
